# Generated by Django 3.2.13 on 2022-07-08 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('local', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, max_length=255, null=True)),
                ('observacion', models.TextField(blank=True, max_length=255, null=True)),
                ('fechaInicio', models.DateField(verbose_name='fecha de inicio')),
                ('fechaFin', models.DateField(verbose_name='fecha de fin')),
                ('horaInicio', models.TimeField(blank=True, null=True, verbose_name='hora de inicio')),
                ('horaFin', models.TimeField(blank=True, null=True, verbose_name='hora de fin')),
                ('diaCompleto', models.BooleanField(default=False, verbose_name='todo el día')),
                ('cantidadParticipante', models.IntegerField(null=True)),
                ('estado', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='solicitudes.estado')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local.local')),
            ],
        ),
    ]
