# Generated by Django 3.2.13 on 2022-07-08 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solicitudes', '0001_initial'),
        ('aseguramiento', '0001_initial'),
        ('local', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aseguramientosolicitud',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudes.solicitud'),
        ),
        migrations.AddField(
            model_name='aseguramientolocal',
            name='aseguramiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aseguramiento.aseguramiento'),
        ),
        migrations.AddField(
            model_name='aseguramientolocal',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local.local'),
        ),
        migrations.AddField(
            model_name='aseguramiento',
            name='tipoAseguramiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aseguramiento.tipoaseguramiento'),
        ),
    ]
