# Generated by Django 3.2.13 on 2022-07-09 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aseguramiento', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aseguramiento',
            options={'verbose_name': 'Aseguramineto', 'verbose_name_plural': 'Aseguramientos'},
        ),
    ]
