# Generated by Django 3.2.13 on 2022-07-08 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, max_length=255, null=True)),
                ('fechaInicio', models.DateField(verbose_name='fecha de inicio')),
                ('fechaFin', models.DateField(verbose_name='fecha de fin')),
                ('horaInicio', models.TimeField(verbose_name='hora de inicio')),
                ('horaFin', models.TimeField(verbose_name='hora de fin')),
            ],
        ),
        migrations.CreateModel(
            name='TipoActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
