# Generated by Django 3.2.13 on 2022-07-08 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actividad', '0001_initial'),
        ('local', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local.local'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='tipoActividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividad.tipoactividad'),
        ),
    ]
