# Generated by Django 3.2.13 on 2022-07-08 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='tipo_usuario',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.tipousuario'),
        ),
    ]
