# Generated by Django 3.2.13 on 2022-07-09 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0002_local_responsables'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='local',
            options={'verbose_name': 'Local', 'verbose_name_plural': 'Locales'},
        ),
    ]
